### ISSUE TITLE
Row operations

### ISSUE THREAD

**Issue by nickmcintyre** [nickmcintyre/numero#2]
Matrices (rank-2 tensors) should support [elementary row operations](https://en.wikipedia.org/wiki/Elementary_matrix#Elementary_row_operations). It'd be neat to use them to teach elimination.

**Comment by nickmcintyre** [comment]
@ashneeldas2 I like your idea for `add(r1, r2)`. That method currently performs element-wise addition, so there are a couple of possibilities. One thought is to pass strings or constants like the following.

```javascript
let t = createTensor([[1, 2], [3, 4]]);
// add row 1 to row 2 in place
t.add(R1, R2); // [[1, 2], [4, 6]]
```
Another is to create special methods for row operations.

```javascript
let t = createTensor([[1, 2], [3, 4]]);
// add row 1 to row 2 in place
t.rowAdd(1, 2); // [[1, 2], [4, 6]]
```

Either could be implemented using a combination of methods for slicing and joining.

**Comment by ashneeldas2** [comment]
@nickmcintyre I’m a fan of the second one because it focuses on usability and simplicity. I would also have the row operations return a value as opposed to overwrite the old matrix; it might be useful to retain the original matrix when doing comparisons and checking for bases etc. 

If this all sounds good to you, I’d love to get started!

**Comment by nickmcintyre** [comment]
Sounds good!

I'm still mulling over static and instance versions of methods–it will probably be case-by-case. For example, p5.Vector's [`add()`](https://p5js.org/reference/#/p5.Vector/add) supports both with the static method returning a new object.

**Comment by nickmcintyre** [comment]
@ashneeldas2 I implemented the Wikipedia example of [Gaussian elimination](https://en.wikipedia.org/wiki/Gaussian_elimination) and ended up extending `addRows()` and `subRows()` with an optional parameter for row multiples (defaults to 1).

```javascript
function setup() {
  const result = num.tidy(() => {
    let a = createTensor([[ 2,  1, -1,   8],
                          [-3, -1,  2, -11],
                          [-2,  1,  2,  -3]]);
    a = a.addRows(0, 1, 1.5);
    a = a.addRows(0, 2);
    a = a.subRows(1, 2, 4);
    a = a.addRows(2, 1, 0.5);
    a = a.subRows(2, 0);
    a = a.mulRow(1, 2);
    a = a.mulRow(2, -1);
    a = a.subRows(1, 0);
    a = a.mulRow(0, 0.5);
    return a;
  });

  print(result.toString());
}
```

Seems pretty close–curious if you think we can make this any more intuitive.

**Comment by ashneeldas2** [comment]
Seems good to go and I think it is pretty intuitive – An enhancement for the future might be to support both instance and static versions, but I think for now this works well!
